---
# Tasks file for monitoring
- name: Install Node-exporter
  include_tasks: node-exporter.yml

- name: Install Docker
  include_tasks: install-docker.yml
  when: ansible_nodename == "{{ monitoring_host }}"

- name: Configure and start Docker
  include_tasks: start-docker.yml
  when: ansible_nodename == "{{ monitoring_host }}"