---
# Tasks file for install node-exporter

- name: Node-exporter | Create directory node-exporter
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/node-exporter
    state: directory
    mode: 0755

- name: Node-exporter | Dowload node-exporter
  become: true
  ansible.builtin.get_url:
    url: "{{ ne_get_url }}"
    dest: /tmp/node-exporter-{{ ne_ver }}.tar.gz

- name: Node-exporter | Extract on /tmp
  become: true
  ansible.builtin.unarchive:
    src: /tmp/node-exporter-{{ ne_ver }}.tar.gz
    dest: /tmp
    mode: 0755
    copy: no

- name: Node-exporter | mv files in directory node-exporter
  become: true
  ansible.builtin.command: mv /tmp/node_exporter-{{ ne_ver }}.linux-amd64/node_exporter {{ ne_dir }}

- name: Node-exporter | Create unit file
  become: true
  ansible.builtin.template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 644

- name: Node-exporter | Enable service 
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes

- name: Node-exporter | Start service
  become: true
  ansible.builtin.systemd:
    state: started
    name: node_exporter
    daemon_reload: yes

- name: Node-exporter | Service status
  become: true
  ansible.builtin.command: systemctl status node_exporter.service
  register: status_ne

- name: Node-exporter | Show status
  debug:
    var: status_ne.stdout_lines